### ISSUE TITLE
Do we want to create a project logo?

### ISSUE THREAD

**Issue by 3osmic** [3osmic/Parking-Lot-System#16]

**Comment by Volatar** [comment]
We would need to find one of our members with rudimentary art skills if we wanted to do this.

**Comment by CaseeNewton** [comment]
Ivan has volunteered via the chat in Practera to create a logo for the project. We can assign that to them. Thanks Ivan!

**Comment by Volatar** [comment]
@ivanwaketech came back with the following logo options:

**Comment by Volatar** [comment]
![image](https://github.com/3osmic/Parking-Lot-System/assets/1719182/1b8cf22f-287d-4912-bfee-0121cfe84534)

**Comment by CaseeNewton** [comment]
I think the 2nd one may be the most simple and easy to understand at a glance. I would personally go with that one.
