### ISSUE TITLE
Project Description SRS: Project Features / Functions, User Stories, Use Case

### ISSUE THREAD

**Issue by 3osmic** [3osmic/Parking-Lot-System#18]

**Comment by 3osmic** [comment]
Need to combine one or more pieces of system functionality to satisfy this use case.

**Comment by 3osmic** [comment]
(Arrows) - Open app scan qr code or scan qr code and open app

 Work on use case diagram

**Comment by CaseeNewton** [comment]
![Image](https://github.com/3osmic/Parking-Lot-System/assets/145292524/c680773e-d5d9-4494-8c74-63eb1cb0bd7b)
