### ISSUE TITLE
Project Collaboration and Documentation SRS: Tools/Platforms

### ISSUE THREAD

**Issue by 3osmic** [3osmic/Parking-Lot-System#19]

**Comment by CaseeNewton** [comment]
•	GitHub – Used for tracking individual and team goals for the project week to week and what is still in a working phase vs what is completed and what needs to be started. 

•	Microsoft Teams – for weekly meetings and chat collaboration

•	Practera – for chat and weekly requirements and documentation from the professor about the timeline for the project. 

•	Email – used to share GoogleDocs and contact team members if needed. (is mostly used to share documents)

•	GoogleDocs – used during our weekly meetings and anytime for the team to add and revise our current documents to submit weekly. Also a chance to collaborate at the same time in one document as we meet each week.
