### ISSUE TITLE
Security/Hardware - SRS V2

### ISSUE THREAD

**Issue by 3osmic** [3osmic/Parking-Lot-System#31]

**Comment by CaseeNewton** [comment]
Created security and hardware requirements for the parking lot project.


Security 
Passwords will be required to have 1 uppercase minimum, 1 lowercase minimum, 1 special character (Ex: * ! @ $ &), and minimum 8 characters long. This will help prevent hacking and provide security for the visitor. 

Passwords will be required to be updated and changed every 90 days.

 Passwords will not be allowed to be any of the previously used passwords from the last 3 used. The user will only be allowed to try for the correct username and password a total of 4 times in a 24-hour period before being locked out of their account. It will only be retrievable by calling or requesting support for verification and reset. This will prevent password crackers from testing multiple times to break into the visitors application.

Minimize external footprint to the server by installing on Wake Tech’s intranet and using latest firewall configurations and using a valid, third-party signed certificate, which ensures a secure connection between the client device and the server.

Hardware

Cell Phone with camera QR scanning capability.

Verification Server

QR code with minimum size of 6in x 6 in. Large enough for easy scanning from a distance for convenience and ease of access.
