### ISSUE TITLE
Architecture - SRS V2

### ISSUE THREAD

**Issue by 3osmic** [3osmic/Parking-Lot-System#33]

**Comment by tjasper123** [comment]
1.	User Interface Layer:
o	Mobile App:
	Generates and displays unique QR codes for parking spots.
	Allows users to scan QR codes for entry and exit.
	Provides mapping and directions to guide users to their parking spots.
	Integrates with the payment system for parking fee transactions.
	Offers push notifications for reminders and assistance requests.
2.	Application Layer:
o	QR Code Generation:
	Generates unique QR codes for each parking spot.
o	QR Code Scanning:
	Scans QR codes using mobile app for entry and exit.
o	Mapping and Directions:
	Provides directions to guide users back to their parking spots.
o	Payment Integration:
	Integrates with payment gateways for secure payment processing.
o	Notification System (S):
	Sends push notifications to remind users of their parking spot and parking duration.
o	Emergency Assistance (S):
	Provides a feature for users to request help or report incidents.
o	Integration with Navigation Apps (C):
	Allows users to export directions to popular navigation apps like Google Maps or Waze.
o	Voice Assistance (C):
	Includes voice-guided navigation for users who prefer audio directions.
o	In-App Customer Support (C):
	Offers in-app customer support for user inquiries and issues.
o	Parking Spot Guidance (C):
	Uses AR (Augmented Reality) to guide users visually to their parking spot.
3.	Backend Services Layer:
o	Database Management:
	Stores data related to parking spot QR codes, user transactions, and assistance requests.
	Ensures data integrity and data retention of user parking history.
o	Security and Authentication:
	Implements role-based access control to restrict system usage to "Student" and "Facility" roles.
o	Performance (NFR):
	Must provide QR code information and parking spot guidance in less than 10 seconds.
o	Reliability (NFR):
	Should find users' parking spot location accurately more than 95% of the time.
o	Availability (NFR):
	Remains operational 24/7, including holidays.
o	Recoverability (NFR):
	Backs up and recovers user data in case of system downtime.
o	Capacity (NFR):
	Handles requests based on the total number of parking spaces.
o	Usability (NFR):
	Ensures the GUI is user-friendly and easy to use.
4.	Infrastructure Layer:
o	Servers and Cloud Services:
	Hosts and manages the software components.
	Ensures high availability, scalability, and performance.
5.	Documentation and User Support:
o	Provides documentation for users, operators, and developers.
